Obsavo demo timing
rapyuta/rplidar_ros pull request #1
Opened 2016-10-03 07:55 UTC by jvgomez

@dominiquehunziker please take a quick look to this. Is mainly adding some comments that were used to analyze the timing and I would like to keep around.

2016-10-04 15:54 UTC, dominiquehunziker requested changes

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +        //ROS_INFO("Time take by full laserscan: %f", (end_scan_time-start_scan_time).toSec());
I would fix the grammar

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +                            float angle = (float)((nodes[i].angle_q6_checkbit >> RPLIDAR_RESP_MEASUREMENT_ANGLE_SHIFT)*0.015625); // /64.0f);
this is now a double literal; convert it to a float literal.

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +                    angle_max = DEG2RAD((float)(nodes[end_node].angle_q6_checkbit >> RPLIDAR_RESP_MEASUREMENT_ANGLE_SHIFT)*0.015625); // /64.0f);
these are now a double literals; convert then to a float literals.

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +        //ROS_INFO("Time take by laserscan transformation: %f", (end_laserscan_time-start_laserscan_time).toSec());
fix grammar

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +              float read_value = (float) nodes[i].distance_q2*0.00025; // /4.0f/1000;
convert to float literal

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +              float read_value = (float)nodes[i].distance_q2*0.00025; // /4.0f/1000;
convert to float literal

2016-10-04 15:54 UTC, dominiquehunziker commented on src/rplidar_nodelet.cpp
> +    scan_duration = (end_scan_time - start_scan_time).toSec();// * 1e-3;
this changes the units of the scan_duration; was this a bug or did you make a mistake here?

2016-10-05 02:06 UTC, jvgomez commented on src/rplidar_nodelet.cpp
> +    scan_duration = (end_scan_time - start_scan_time).toSec();// * 1e-3;
When I did the timing, I timed the whole loop into 3 different parts: data acquisition from serial, transformation to ROS LaserScan and publishing, and the total (which should be the sum). Without this change, times will not match. This value is later assigned to scan_time, which is "time between scans [s]". In fact, I am still not sure if this is the correct time, as it does not measure exactly time between scans. But, in any case, I think it was a bug.

2016-10-05 02:19 UTC, jvgomez commented
@dominiquehunziker comments addressed. I do not really know how this new Review feature from github works yet, I do not know if I have to do anything else to notify changes or what.

2016-10-05 15:55 UTC, dominiquehunziker approved these changes

2016-10-05 15:56 UTC, merged